### ISSUE TITLE
CDMUtil Console App requirements

### ISSUE THREAD

**Issue by Tad1011** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#100]
Customers reported when they run CDMUtil Console App in their local machine with Windows 10 Pro build version:19042.1526 and immediately this App is closed. Are there OS version requirements to use CDMUtil Console App?

**Comment by jiyada** [comment]
There is no requirement of OS version.. however error may be due to missing NET Libraries. installing .NET46 version might solve the problem (https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net462-developer-pack-offline-installer). Please open the issue if this does not solve

**Comment by SriRayala** [comment]
@jiyada - Hi Jila, I've successfully ran the Console app on my old PC, but I'm unable to run it on my PC which uses AMD Ryzen. The terminal just opens and closes right away without showing any error messages. Have you seen this error before? I've installed the above framework you suggested, however still having the same issue.

Any help would be greatly appreciated.
