### ISSUE TITLE
Azure Function - manifestToSQLDDL 

### ISSUE THREAD

**Issue by patrickjlking** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#112]
Code snippet below under CDMUtil_AzureFunctions/CDMUtil.cs in the manifestToSQLDDL Function is a bug and if/else statement should be the other way around

if (!String.IsNullOrEmpty(c.synapseOptions.targetSparkEndpoint))
{
statementsList = await SQLHandler.sqlMetadataToDDL(metadataList, c, log);
}
else
{
statementsList = SparkHandler.metadataToSparkStmt(metadataList, c, log);
}

**Comment by jiyada** [comment]
this is fixed in latest version
