### ISSUE TITLE
Incremental CDCCopy not taking the lastest action

### ISSUE THREAD

**Issue by A009948** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#113]
The Source query on the incremental pipeline is doing an order by Start_LSN DESC. We have noticed for tables like InventTrans the sort is causing the incremental to not take the latest action for the recID in the cdc file. We have changed the query to order by DataLakeModified_DateTime DESC, that way it picks up the latest change for each recID. 

Select DML_Action, @{pipeline().parameters.COLUMN_NAMES}
        FROM 
        (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY RECID ORDER BY **DataLakeModified_DateTime** DESC) AS ROWNO FROM @{pipeline().parameters.CDC_TABLE_NAME}
WHERE [$FileName] > '@{pipeline().parameters.LAST_PROCESSED_FILE_NAME}'  OR
[$FileName] = '@{pipeline().parameters.LAST_UPDATED_CDC_FILE}' 
        ) AS X
        WHERE X.ROWNO = 1

**Comment by dan-we** [comment]
I've seen this happen as well.  An important note is that the `Start_LSN` values are identical when there are multiple DML actions within the same transaction.  For example:
![image](https://user-images.githubusercontent.com/32401871/174857203-bcd6be38-e342-465b-be31-f60bfba608d4.png)
`Seq_Val`, I believe, should identify the sequence within that.

**Comment by jiyada** [comment]
The new pipeline include the datalakemodified_datetime as part of the query
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/master/Analytics/ArchitecturePatterns/SQLIntegration/IncrementalExport_SQL.zip
