### ISSUE TITLE
SynapseToSQL_ADF - SynapseToSQL_DestSetupScript.sql - bug in Merge Statement

### ISSUE THREAD

**Issue by peterdev1979** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#118]
There seems to be an bug in the MERGECDC stored procedure.

When a record is inserted and then deleted, the procedure will try to merge the line with the last action (a delete) with the target table, where it might not yet exist. This will result in an insert (`WHEN NOT MATCHED BY TARGET THEN INSERT` ....), but it should just ignore the record.

It should only insert a record when it is a Insert or Update action (i.e. not a delete), so the statement (line 83 in the source) should be
`' WHEN NOT MATCHED BY TARGET and S.DML_Action <> ''DELETE'' THEN INSERT (' + `...

**Comment by A009948** [comment]
> 

We ran into this as well. I added another delete statement at the bottom to run the delete again. Not efficient but it works since the first 'Delete' inserted the record. Now the second 'Delete' actually deletes it.

**Comment by jiyada** [comment]
thanks for the input - we will test the suggestion and update the template

**Comment by jiyada** [comment]
Thanks for the feedback. This is fixed in the updated pipeline - 
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/master/Analytics/ArchitecturePatterns/SQLIntegration/IncrementalExport_SQL.zip
