### ISSUE TITLE
Azure function 'createManifest' failed with status-'InternalServerError' 

### ISSUE THREAD

**Issue by apsych** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#12]
I am getting the below error, on Activity name 'GenerateCDM' 
Did someone had the same issue? Do I have to change somewhere the time out of the Azure function?

`Operation on target createEntity failed: Call to provided Azure function 'createManifest' failed with status-'InternalServerError' and message - '<html><head><title>500 - The request timed out.</title></head><body> <font color ="#aa0000"> <h2>500 - The request timed out.</h2></font> The web server failed to respond within the specified time.</body></html>'.`

![image](https://user-images.githubusercontent.com/13466599/112639707-dce55400-8e40-11eb-8fdc-3719443cc9a9.png)

**Comment by robnzl** [comment]
Check the function app has permissions correctly set for blob storage access, and that you have not included the https:// in the storage URL.

**Comment by jiyada** [comment]
closing issue as no comment received.
