### ISSUE TITLE
Create T-SQL For SQL Server

### ISSUE THREAD

**Issue by kdubious** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#13]
If I wanted to create a SQL Server DB from the CDM, can this project help with that?

**Comment by jiyada** [comment]
Not sure whats the intent here. Can you please clarify

**Comment by kdubious** [comment]
I like the fact that there exists a database schema which covers many common use cases. I can's find a SQL Script I can use to build an empty database with this schema. Can I do that with this project?

**Comment by jiyada** [comment]
This project is not for the SQL Server database creation. This is primarily focused on reading common data model (CDM) and creating views or external tables on Synapse Analytics.

**Comment by kdubious** [comment]
@jiyada I understand... I just can't seem to find the SQL Schema anywhere, so I was asking.
