### ISSUE TITLE
External Tables Created Over Synapse Serverless Throw Exceptions

### ISSUE THREAD

**Issue by divyar-mmjs** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#145]
We have utilized the CDMUtil for creating the D365 tables as External Tables over Synapse Serverless Pool. Further there are pipelines to build the entities and populate them in a datawarehouse.
However, we have noticed below exceptions in our ADF pipelines every now and then in Production Environment:
"Type=System.Data.SqlClient.SqlException,Message=Error handling external file: 'Unexpected end-of-input within record at [byte: 137678920]."

Re-running the pipelines after some time generally resolves the issue. We have a understanding that this occurs when export to datalake utility fromD365 is writing data to DataLake. Is there any way to identify when the files are being written to avoid reading data at that time.
Or is there a way to identify a timeslot which is a good time to pull data from the external tables?

**Comment by jiyada** [comment]
Your assumption is correct when you are reading the data from data lake, if the files are changing in the data lake - you may get this error. Unfortunately, there is no way to know to predict when the data will be updated. With near real feature on - data will be updated in the lake within minutes when data changes happen in the source system. If the data does not change in the source system there will be no changes in the files. Best way to handle this situation is implementing re-try logic in your code we have heard from other customer that retry usually solves the problem as data changes are not continous.
