### ISSUE TITLE
ADF pipeline SQLTablesToADLS

### ISSUE THREAD

**Issue by parasparekh** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#15]
I wonder where I can find the scripts to create tables CustTable & CustGroup in the source Azure SQL DB that this ADF pipeline is passing to the Azure Function.

**Comment by parasparekh** [comment]
I wonder if anyone is assigned to look into this.

**Comment by jiyada** [comment]
CustTable and CustGroup are table that exists in Dynamics AX database. Pipeline is generic so if you have other tables in your database you can change the parameter and pass those tables.
