### ISSUE TITLE
Binary datatype is not supported in attributeToSQLType method in CDMUtil

### ISSUE THREAD

**Issue by russtolsma** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#150]
The CDMUtil application is missing support for column definitions of type 'Binary'.  When the DDL is being generated the case is not being met within the following method:
`static public string attributeToSQLType(ColumnAttribute attribute, SynapseDBOptions synapseDBOptions)`

which results in an error being generated when executing the DDL as it assigned a default type of `nvarchar(60)`.

Recommendation per @jiyada is for the following code to be included in the case statement:

`case "binary":`
`sqlColumnDef = $"{attribute.name} varbinary(100)";`
` break;`

Hope this helps.

**Comment by jiyada** [comment]
This has been fixed in the latest version
