### ISSUE TITLE
SynapseToSQL_ADF IncrementalExport_SQL Merge Activity not working correctly

### ISSUE THREAD

**Issue by viktorari** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#155]
In the last step of the Merge Activity in the IncrementalExport pipeline, the input for the @TargetTable variable is on the form [Schema].[TableName]

![Merge Activity Input ](https://user-images.githubusercontent.com/92576881/187174555-9c0e91f0-38a2-4484-a191-b8ddec37dafc.png)

In the Script task of the Merge Activity the first part of the query which sets the @UpdateColumns and @Columns variables doesn't return a result because in the where clause the TABLE_NAME column form INFORMATION_SCHEMA.COLUMSN is being evaluated to [Schema].[TableName].

![image](https://user-images.githubusercontent.com/92576881/187175376-a470ff5a-2ccd-4896-a607-6043e25c7e95.png)

This can be fixed by changing the where clause to _WHERE CONCAT(TABLE_SCHEMA,'.',TABLE_NAME) = @TargetTable_

**Comment by jiyada** [comment]
Thanks for raising the issue..Closing the issue with attached pull request
