### ISSUE TITLE
CDMUtil Azure function or consol app fails to create synapse objects: Unable to cast object

### ISSUE THREAD

**Issue by asarvankar** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#174]
Hi,

Tried to run latest version of the code as console app and Azure function.

Both the methods lead to same error:

unable to cast object:

![image](https://user-images.githubusercontent.com/117209331/200072185-3f306d68-3324-4a10-a6e1-800b1037a758.png)

Please let me know if there are any potential fixes for this

Thanks

**Comment by jiyada** [comment]
Have not seen this error with other customer - it seems like metadata files (cdm.json) may be corrupted. Can you deactivate a table , wait for metadata to be refreshed and then try again. I am closing the issue with comment but you can open it up if the issue persists.

**Comment by asarvankar** [comment]
I have used metadata.json files provided as part of CDM repo at https://github.com/microsoft/CDM/tree/master/schemaDocuments/core/operationsCommon
