### ISSUE TITLE
CDMUtil  runtime version not supported anymore

### ISSUE THREAD

**Issue by jonascnockaert** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#183]
Azure Function runtime version of CDMUtil (3.1) not supported anymore:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-csharp#run-the-pre-upgrade-validator

**Comment by TenorSax4u** [comment]
Please fix this as soon as possible!   This utility is critical in our ability to research and consume FnO data.  Also, the download zip file gives error when unzipping - file name is to long.
