### ISSUE TITLE
Issue while  executing CDMUtilConsoleApp 

### ISSUE THREAD

**Issue by DAXlearning** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#187]
Hi

We have download the CDMUtilConsoleApp and update the below parameters  as below

<add key="TenantId" value="XXXXXXXXXXXXXX"/>
    <add key="AccessKey" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />
    <add key="ManifestURL" value="https://StorageAccount.blob.core.windows.net/dynamics365-financeandoperations/MyEnv.sandbox.operations.dynamics.com/Tables/Tables.manifest.cdm.json" />
    <add key="TargetDbConnectionString" value="Server=MyServer-ondemand.sql.azuresynapse.net;Initial Catalog=DBName;Authentication='Active Directory Integrated'" />

Whenever we are trying to execute the  ConsoleApp, it starts and Disappears. Let us know, if we are missing any DLL's.

Tried using on Azure Dev VM.

**Comment by jiyada** [comment]
You can try running the console app with command line or powershell and see the steps that is failing.

**Comment by jiyada** [comment]
closing the issue - please re-open if you still have issue
