### ISSUE TITLE
Creation of Changefeed structure

### ISSUE THREAD

**Issue by JPremnath06** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#188]
Hi Everyone,

I'm trying to Implement a CDMUtil solution for Tier 1 box. Using CDMUtil, I'm able to create **Tables.manifest.cdm.json**.

My Question - Is it possible to create a change feed file structure using CDMUtil solution or any other?

Thanks,
Premnath

**Comment by jiyada** [comment]
CDMUtil does not create changefeed structure - export data from tier 1 was supported just for simulation purposes during the Export to data lake preview. I would recommend not to use this feature rather use Export to data lake feature with Tier 2 or higher environment.
