### ISSUE TITLE
IncrementalExport_SQL ADF -- No filename field?

### ISSUE THREAD

**Issue by GWCS** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#190]
In the Step CDCCopy, the query is not working.  It says invalid column [$FileName].It looks like in those changed feed files, there is no field for storing File Name.

Does anyone know? 

Thank you

Select DML_Action, @{item().COLUMN_NAMES}
		FROM 
		(
			SELECT *, ROW_NUMBER() OVER (PARTITION BY RECID ORDER BY Start_LSN, Seq_Val, DataLakeModified_DateTime DESC) AS ROWNO FROM @{item().CDC_TABLE_NAME}
WHERE **[$FileName]** > '@{item().LAST_PROCESSED_FILE_NAME}'  OR
**[$FileName]** = '@{item().LAST_UPDATED_CDC_FILE}' 
		) AS X
		WHERE X.ROWNO = 1

**Comment by jiyada** [comment]
$FileName is created in serverless view when DDLType SynapseServerlessView option is used. For external table this field is not created.
