### ISSUE TITLE
Missing dbo.SynapseToSQLUpdatedTables script

### ISSUE THREAD

**Issue by StefaanTa** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#28]
Hi I'm trying to implement FactsTrack SynapseToSQL but it seems I'm missing the script for the table dbo.SynapseToSQLUpdatedTables.
Can somebody help?
Thx

**Comment by A009948** [comment]
Is there any update on this? I also am running into this issue and I am not seeing an updated SQL destination file.

**Comment by jiyada** [comment]
We updated the solution of the Synapse to SQL ADF/Synapse pipeline template.. this no longer user any source or target sql scripts to be deployed separately .. pipeline uses all the scripting within the pipeline and simplified pipelines. Try this out 
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/tree/master/Analytics/SynapseToSQL_ADF
