### ISSUE TITLE
@translateBYOD_enums int = 1

### ISSUE THREAD

**Issue by Roelemansk** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#347]
This was added but i think this parameter is forgotten in step02: https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/master/Analytics/DataverseLink/VirtualDatawarehouse/Step2_1_EDL_To_SynapseLinkDV_DataVirtualization.sql. All other parameters are required to be set there but IT is missing. For now I have hard set it to 0 to het the code working. Please add the parameter.

**Comment by sbkoppens** [comment]
@Roelemansk thank you for bringing that to my attention, it has now been fixed.
