### ISSUE TITLE
SQLToADLSFullExport: Duplicated variables in DataFactory

### ISSUE THREAD

**Issue by robnzl** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#5]
After deploying the data factory ARM template, I have duplicated variables in the GenerateCDM pipeline, Set variable step. After validating the resources, we receive the errors below. The variables do show twice on the variable tab.

Failed to publish change(s) because of the following validation error(s). Fix error(s) to continue publishing.
GenerateCDM
The name 'MANIFESTDEFINITION' is duplicated in 2 variables.
GenerateCDM
The name 'ENTITYDEFINITION' is duplicated in 2 variables.
GenerateCDM
The name 'MANIFESTBODY' is duplicated in 2 variables.

**Comment by thomastmo** [comment]
Hello,

The ADF pipeline doesn't generate manifests files.

- ADF pipeline is deployed and can be executed without any error. It generates CustTable.csv and CustGroup.csv.
- The createManifest function response code is 200 OK, and the HTTP reponse content is {"ManifestName":"Group","IsManifestCreated":false}

I already check Azure Function rights on Storage Account, do you have any idea how I can solve this issue ?

Thanks for your help.

Regards

**Comment by jiyada** [comment]
Closing due to old issue. If the issue persist and need clarification please open a new issue or reopen the issue
