### ISSUE TITLE
ModelJsonToViewDefinition.sql is only for one entity?

### ISSUE THREAD

**Issue by sa0479** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#6]
Hello
Is "ModelJsonToViewDefinition.sql" intended to create VIEW definition only for one entity in model.json? Is works OK for one entity, but if model.json contain multiple entites, I get a mess in statement to create VIEW defintion.
What is an approach to create multiple views for multiple entities in model.json?

Below is my model.json, it is generated by export Entity Store from D365FFO 10.0.15 PEAP:
SET @json = N'{
  "application": "Dynamics 365 for Finance and Operations",
  "name": "EntAssetAggregateMeasurement",
  "description": "EntAssetAggregateMeasurement",
  "version": "1.0",
  "culture": "en-US",
  "modifiedTime": "2020-11-20T07:59:40.8984148+00:00",
  "annotations": [
    {
      "name": "D365FO:ApplicationBuildVersion",
      "value": "10.0.569.13"
    },
    {
      "name": "D365FO:ModelName",
      "value": "EntAssetAggregateMeasurement"
    },
    {
      "name": "D365FO:ModelPublisher",
      "value": "Microsoft"
    }
  ],
  "entities": [
    {
      "$type": "LocalEntity",
      "name": "EntAssetAggregateMeasurement_Company",
      "description": "BICompanyView",
      "attributes": [
        {
          "name": "ROW_UNIQUEKEY",
          "description": "ROW_UNIQUEKEY",
          "dataType": "int64"
        },
        {
          "name": "COMPANYNAME",
          "description": "COMPANYNAME",
          "dataType": "string"
        },
        {
          "name": "ISVIRTUAL_VALUE",
          "description": "ISVIRTUAL_VALUE",
          "dataType": "int64"
        },
        {
          "name": "COMPANY",
          "description": "COMPANY",
          "dataType": "string"
        },
        {
          "name": "PARTITION",
          "description": "PARTITION",
          "dataType": "int64"
        },
        {
          "name": "RECID",
          "description": "RECID",
          "dataType": "int64"
        },
        {
          "name": "ISVIRTUAL",
          "description": "ISVIRTUAL",
          "dataType": "string"
        }
      ],
      "partitions": [
        {
          "name": "EntAssetAggregateMeasurement_Company",
          "location": "https://awavanilladatalake.blob.core.windows.net/dynamics365-financeandoperations/awa-vanilla-test9363dbde6c85033cdevaos.cloudax.dynamics.com/AggregateMeasurements/EntAssetAggregateMeasurement/EntAssetAggregateMeasurement_Company/EntAssetAggregateMeasurement_CompanyFile0.csv"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "EntAssetAggregateMeasurement_Date_",
      "description": "BIDateDimensionValue",
      "attributes": [
        {
          "name": "ROW_UNIQUEKEY",
          "description": "ROW_UNIQUEKEY",
          "dataType": "int64"
        },
        {
          "name": "DATE_",
          "description": "DATE_",
          "dataType": "dateTime"
        },
        {
          "name": "WEEK",
          "description": "WEEK",
          "dataType": "dateTime"
        },
        {
          "name": "TENDAYS",
          "description": "TENDAYS",
          "dataType": "dateTime"
        },
        {
          "name": "MONTH",
          "description": "MONTH",
          "dataType": "dateTime"
        },
        {
          "name": "QUARTER",
          "description": "QUARTER",
          "dataType": "dateTime"
        },
        {
          "name": "TRIMESTER",
          "description": "TRIMESTER",
          "dataType": "dateTime"
        },
        {
          "name": "HALFYEAR",
          "description": "HALFYEAR",
          "dataType": "dateTime"
        },
        {
          "name": "YEAR",
          "description": "YEAR",
          "dataType": "dateTime"
        },
        {
          "name": "DAYOFWEEK",
          "description": "DAYOFWEEK",
          "dataType": "int64"
        },
        {
          "name": "DAYOFTENDAYS",
          "description": "DAYOFTENDAYS",
          "dataType": "int64"
        },
        {
          "name": "DAYOFMONTH",
          "description": "DAYOFMONTH",
          "dataType": "int64"
        },
        {
          "name": "DAYOFQUARTER",
          "description": "DAYOFQUARTER",
          "dataType": "int64"
        },
        {
          "name": "DAYOFTRIMESTER",
          "description": "DAYOFTRIMESTER",
          "dataType": "int64"
        },
        {
          "name": "DAYOFHALFYEAR",
          "description": "DAYOFHALFYEAR",
          "dataType": "int64"
        },
        {
          "name": "DAYOFYEAR",
          "description": "DAYOFYEAR",
          "dataType": "int64"
        },
        {
          "name": "WEEKOFMONTH",
          "description": "WEEKOFMONTH",
          "dataType": "int64"
        },
        {
          "name": "WEEKOFQUARTER",
          "description": "WEEKOFQUARTER",
          "dataType": "int64"
        },
        {
          "name": "WEEKOFTRIMESTER",
          "description": "WEEKOFTRIMESTER",
          "dataType": "int64"
        },
        {
          "name": "WEEKOFHALFYEAR",
          "description": "WEEKOFHALFYEAR",
          "dataType": "int64"
        },
        {
          "name": "WEEKOFYEAR",
          "description": "WEEKOFYEAR",
          "dataType": "int64"
        },
        {
          "name": "TENDAYSOFMONTH",
          "description": "TENDAYSOFMONTH",
          "dataType": "int64"
        },
        {
          "name": "TENDAYSOFQUARTER",
          "description": "TENDAYSOFQUARTER",
          "dataType": "int64"
        },
        {
          "name": "TENDAYSOFTRIMESTER",
          "description": "TENDAYSOFTRIMESTER",
          "dataType": "int64"
        },
        {
          "name": "TENDAYSOFHALFYEAR",
          "description": "TENDAYSOFHALFYEAR",
          "dataType": "int64"
        },
        {
          "name": "TENDAYSOFYEAR",
          "description": "TENDAYSOFYEAR",
          "dataType": "int64"
        },
        {
          "name": "MONTHOFQUARTER",
          "description": "MONTHOFQUARTER",
          "dataType": "int64"
        },
        {
          "name": "MONTHOFTRIMESTER",
          "description": "MONTHOFTRIMESTER",
          "dataType": "int64"
        },
        {
          "name": "MONTHOFHALFYEAR",
          "description": "MONTHOFHALFYEAR",
          "dataType": "int64"
        },
        {
          "name": "MONTHOFYEAR",
          "description": "MONTHOFYEAR",
          "dataType": "int64"
        },
        {
          "name": "QUARTEROFHALFYEAR",
          "description": "QUARTEROFHALFYEAR",
          "dataType": "int64"
        },
        {
          "name": "QUARTEROFYEAR",
          "description": "QUARTEROFYEAR",
          "dataType": "int64"
        },
        {
          "name": "TRIMESTEROFYEAR",
          "description": "TRIMESTEROFYEAR",
          "dataType": "int64"
        },
        {
          "name": "HALFYEAROFYEAR",
          "description": "HALFYEAROFYEAR",
          "dataType": "int64"
        },
        {
          "name": "DATEKEY",
          "description": "DATEKEY",
          "dataType": "int64"
        },
        {
          "name": "BIDATEGREGORIAN",
          "description": "BIDATEGREGORIAN",
          "dataType": "int64"
        },
        {
          "name": "MONTHGREGORIAN",
          "description": "MONTHGREGORIAN",
          "dataType": "int64"
        },
        {
          "name": "QUARTERGREGORIAN",
          "description": "QUARTERGREGORIAN",
          "dataType": "int64"
        },
        {
          "name": "YEARGREGORIAN",
          "description": "YEARGREGORIAN",
          "dataType": "int64"
        },
        {
          "name": "RECID",
          "description": "RECID",
          "dataType": "int64"
        },
        {
          "name": "CALENDARNAME",
          "description": "CALENDARNAME",
          "dataType": "string"
        }
      ],
      "partitions": [
        {
          "name": "EntAssetAggregateMeasurement_Date_",
          "location": "https://awavanilladatalake.blob.core.windows.net/dynamics365-financeandoperations/awa-vanilla-test9363dbde6c85033cdevaos.cloudax.dynamics.com/AggregateMeasurements/EntAssetAggregateMeasurement/EntAssetAggregateMeasurement_Date_/EntAssetAggregateMeasurement_Date_File0.csv"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "EntAssetAggregateMeasurement_EntAssetActiveRequestView",
      "description": "EntAssetActiveRequestView",
      "attributes": [
        {
          "name": "ROW_UNIQUEKEY",
          "description": "ROW_UNIQUEKEY",
          "dataType": "int64"
        },
        {
          "name": "NOOFREQUESTS",
          "description": "NOOFREQUESTS",
          "dataType": "string"
        },
        {
          "name": "DATAAREAID",
          "description": "DATAAREAID",
          "dataType": "string"
        },
        {
          "name": "PARTITION",
          "description": "PARTITION",
          "dataType": "int64"
        },
        {
          "name": "RECID",
          "description": "RECID",
          "dataType": "int64"
        },
        {
          "name": "REQUESTIDENTIFIER",
          "description": "REQUESTIDENTIFIER",
          "dataType": "string"
        },
        {
          "name": "REQUESTTYPE",
          "description": "REQUESTTYPE",
          "dataType": "string"
        },
        {
          "name": "SERVICELEVEL",
          "description": "SERVICELEVEL",
          "dataType": "int64"
        },
        {
          "name": "REQUESTLIFECYCLESTATE",
          "description": "REQUESTLIFECYCLESTATE",
          "dataType": "int64"
        },
        {
          "name": "REQUESTAGE",
          "description": "REQUESTAGE",
          "dataType": "int64"
        }
      ],
      "partitions": [
        {
          "name": "EntAssetAggregateMeasurement_EntAssetActiveRequestView",
          "location": "https://awavanilladatalake.blob.core.windows.net/dynamics365-financeandoperations/awa-vanilla-test9363dbde6c85033cdevaos.cloudax.dynamics.com/AggregateMeasurements/EntAssetAggregateMeasurement/EntAssetAggregateMeasurement_EntAssetActiveRequestView/EntAssetAggregateMeasurement_EntAssetActiveRequestViewFile0.csv"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "EntAssetAggregateMeasurement_EntAssetWorkOrderView",
      "description": "EntAssetWorkOrderView",
      "attributes": [
        {
          "name": "ROW_UNIQUEKEY",
          "description": "ROW_UNIQUEKEY",
          "dataType": "int64"
        },
        {
          "name": "SCHEDULED",
          "description": "SCHEDULED",
          "dataType": "int64"
        },
        {
          "name": "COMPLETED",
          "description": "COMPLETED",
          "dataType": "int64"
        },
        {
          "name": "DELAYED",
          "description": "DELAYED",
          "dataType": "int64"
        },
        {
          "name": "ACTIVE_VALUE",
          "description": "ACTIVE_VALUE",
          "dataType": "int64"
        },
        {
          "name": "SCHEDULEDFORTODAY",
          "description": "SCHEDULEDFORTODAY",
          "dataType": "int64"
        },
        {
          "name": "DATAAREAID",
          "description": "DATAAREAID",
          "dataType": "string"
        },
        {
          "name": "PARTITION",
          "description": "PARTITION",
          "dataType": "int64"
        },
        {
          "name": "RECID",
          "description": "RECID",
          "dataType": "int64"
        },
        {
          "name": "STARTDATE",
          "description": "STARTDATE",
          "dataType": "dateTime"
        },
        {
          "name": "SERVICELEVEL",
          "description": "SERVICELEVEL",
          "dataType": "int64"
        },
        {
          "name": "WORKORDERTYPEID",
          "description": "WORKORDERTYPEID",
          "dataType": "string"
        },
        {
          "name": "EntAssetAggregateMeasurement_WorkOrderType_FK",
          "description": "EntAssetAggregateMeasurement_WorkOrderType_FK",
          "dataType": "int64"
        },
        {
          "name": "EntAssetAggregateMeasurement_WorkOrderServiceLevel_FK",
          "description": "EntAssetAggregateMeasurement_WorkOrderServiceLevel_FK",
          "dataType": "int64"
        }
      ],
      "partitions": [
        {
          "name": "EntAssetAggregateMeasurement_EntAssetWorkOrderView",
          "location": "https://awavanilladatalake.blob.core.windows.net/dynamics365-financeandoperations/awa-vanilla-test9363dbde6c85033cdevaos.cloudax.dynamics.com/AggregateMeasurements/EntAssetAggregateMeasurement/EntAssetAggregateMeasurement_EntAssetWorkOrderView/EntAssetAggregateMeasurement_EntAssetWorkOrderViewFile0.csv"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "EntAssetAggregateMeasurement_WorkOrderServiceLevel",
      "description": "EntAssetWorkOrderServiceLevel",
      "attributes": [
        {
          "name": "ROW_UNIQUEKEY",
          "description": "ROW_UNIQUEKEY",
          "dataType": "int64"
        },
        {
          "name": "WORKORDERSERVICELEVEL",
          "description": "WORKORDERSERVICELEVEL",
          "dataType": "int64"
        },
        {
          "name": "DATAAREAID",
          "description": "DATAAREAID",
          "dataType": "string"
        },
        {
          "name": "SERVICELEVELNAME",
          "description": "SERVICELEVELNAME",
          "dataType": "string"
        },
        {
          "name": "PARTITION",
          "description": "PARTITION",
          "dataType": "int64"
        },
        {
          "name": "RECID",
          "description": "RECID",
          "dataType": "int64"
        }
      ],
      "partitions": [
        {
          "name": "EntAssetAggregateMeasurement_WorkOrderServiceLevel",
          "location": "https://awavanilladatalake.blob.core.windows.net/dynamics365-financeandoperations/awa-vanilla-test9363dbde6c85033cdevaos.cloudax.dynamics.com/AggregateMeasurements/EntAssetAggregateMeasurement/EntAssetAggregateMeasurement_WorkOrderServiceLevel/EntAssetAggregateMeasurement_WorkOrderServiceLevelFile0.csv"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "EntAssetAggregateMeasurement_WorkOrderType",
      "description": "EntAssetWorkOrderType",
      "attributes": [
        {
          "name": "ROW_UNIQUEKEY",
          "description": "ROW_UNIQUEKEY",
          "dataType": "int64"
        },
        {
          "name": "WORKORDERTYPE",
          "description": "WORKORDERTYPE",
          "dataType": "string"
        },
        {
          "name": "DATAAREAID",
          "description": "DATAAREAID",
          "dataType": "string"
        },
        {
          "name": "WORKORDERTYPENAME",
          "description": "WORKORDERTYPENAME",
          "dataType": "string"
        },
        {
          "name": "PARTITION",
          "description": "PARTITION",
          "dataType": "int64"
        },
        {
          "name": "RECID",
          "description": "RECID",
          "dataType": "int64"
        }
      ],
      "partitions": [
        {
          "name": "EntAssetAggregateMeasurement_WorkOrderType",
          "location": "https://awavanilladatalake.blob.core.windows.net/dynamics365-financeandoperations/awa-vanilla-test9363dbde6c85033cdevaos.cloudax.dynamics.com/AggregateMeasurements/EntAssetAggregateMeasurement/EntAssetAggregateMeasurement_WorkOrderType/EntAssetAggregateMeasurement_WorkOrderTypeFile0.csv"
        }
      ]
    }
  ],
  "relationships": [
    {
      "$type": "SingleKeyRelationship",
      "fromAttribute": {
        "entityName": "EntAssetAggregateMeasurement_EntAssetWorkOrderView",
        "attributeName": "EntAssetAggregateMeasurement_WorkOrderType_FK"
      },
      "toAttribute": {
        "entityName": "EntAssetAggregateMeasurement_WorkOrderType",
        "attributeName": "ROW_UNIQUEKEY"
      }
    },
    {
      "$type": "SingleKeyRelationship",
      "fromAttribute": {
        "entityName": "EntAssetAggregateMeasurement_EntAssetWorkOrderView",
        "attributeName": "EntAssetAggregateMeasurement_WorkOrderServiceLevel_FK"
      },
      "toAttribute": {
        "entityName": "EntAssetAggregateMeasurement_WorkOrderServiceLevel",
        "attributeName": "ROW_UNIQUEKEY"
      }
    },
    {
      "$type": "SingleKeyRelationship",
      "fromAttribute": {
        "entityName": "EntAssetAggregateMeasurement_EntAssetWorkOrderView",
        "attributeName": "startDate"
      },
      "toAttribute": {
        "entityName": "EntAssetAggregateMeasurement_Date_",
        "attributeName": "Date_"
      }
    },
    {
      "$type": "SingleKeyRelationship",
      "fromAttribute": {
        "entityName": "EntAssetAggregateMeasurement_EntAssetWorkOrderView",
        "attributeName": "DATAAREAID"
      },
      "toAttribute": {
        "entityName": "EntAssetAggregateMeasurement_Company",
        "attributeName": "Company"
      }
    },
    {
      "$type": "SingleKeyRelationship",
      "fromAttribute": {
        "entityName": "EntAssetAggregateMeasurement_EntAssetActiveRequestView",
        "attributeName": "DATAAREAID"
      },
      "toAttribute": {
        "entityName": "EntAssetAggregateMeasurement_Company",
        "attributeName": "Company"
      }
    }
  ]
}';

**Comment by jiyada** [comment]
try using the console app or cdm solution using it also support model.json . https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/tree/master/Analytics/CDMUtilSolution#option-1---cdmutil-console-app
