### ISSUE TITLE
CDMUtil - Synapse serverless default settings set incorrectly when port specified in SQL Target connection string

### ISSUE THREAD

**Issue by gregorosaurus** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#60]
Hello! 

It looks like when you specify the port in the target connection string in CDMUtil, (example: ```blah-ondeman.sql.azuresynapse.net,1433```), the DateTimeAsString and ConvertDateTime are not set to true. Further, other synapse serverless default settings are not set. 

From what I can see, this is caused by the ObjectDefinitions.cs file incorrectly determining the synapse serverless settings by checking ```.EndsWith("-ondemand.sql.azuresynapse.net")```.  If a port is specified (which will be if you copy the connection string from the synapse workspace portal), this conditional will fail, causing CDMUtil to not set the default synapse serverless settings..  
My thinking is to use ```.Contains("-ondemand.sql.azuresynapse.net")```, rather than EndsWith.  I think this should work better. 

Thanks!

**Comment by jiyada** [comment]
Thanks for the feedback and pointing out the code .. we will address the issue in next iteration

**Comment by jiyada** [comment]
fixed in the new version
