### ISSUE TITLE
CDMUtil DML_Action and Update_Mask incorrect length in generated SQL Views

### ISSUE THREAD

**Issue by gregorosaurus** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#62]
Hello!

It looks like an update to the CDM Utility set the max length of DML_Action and Update_Mask to 5.  

```
if (typeAttributeDefinition.Name.ToLower() == "dml_action" ||
    typeAttributeDefinition.Name.ToLower() == "update_mask")
{
    maximumLenght = 5;
}
```

INSERT and AFTER_UPDATE have lengths greater than 5.  Querying a change feed view results in an error.
```Error handling external file: 'Max errors count reached.'. File/External table name:```

The correct length should be higher. Looks like it should be 12.  

Thanks!

**Comment by jiyada** [comment]
This is fixed in latest version of the CDMIUtil

**Comment by gregorosaurus** [comment]
Awesome thanks! :)

**Comment by gregorosaurus** [comment]
Looks like 15 is still not long enough for update_mask. 

Attached a screenshot. 
<img width="807" alt="2021-11-18 14_20_56-New Window _ Microsoft Teams" src="https://user-images.githubusercontent.com/38509083/142498700-6be4ba38-cdcd-4453-b86a-81e762e8c857.png">

Sorry about being such a bother! :)

**Comment by gregorosaurus** [comment]
Another Screenshot for a large update_mask we found. 
<img width="488" alt="2021-11-18 14_30_39-New Window _ Microsoft Teams" src="https://user-images.githubusercontent.com/38509083/142499946-cf01327e-8050-4db5-939e-4a874ff01cb7.png">

**Comment by scleynen** [comment]
Hi @gregorosaurus  I Was wondering how where you do this query. Is it a VIEW based on the ChangeFeed? So yes, how did you manage to set this up that those VIEWS are generated automatically?

**Comment by gregorosaurus** [comment]
The views are generated with the CDM utility under the analytics folder in this directory. 
The views will be produced based on the manifest file. You run it once for the table manifest file, and one for the change feed manifest file.  You create the views in separate schemas.  There some documentation in the repo, but I'd have to go hunt for it again.
