### ISSUE TITLE
D365FO Export to DataLake AddOn does not trigger ADF Storage Event

### ISSUE THREAD

**Issue by torstenfinndorf** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#63]
Hi,
i have installed the ADF Pipelines like described. 
If a new blob is created from the D365FO DataLakeExport Addon the ADF Blob Storage Event Trigger does not fire.
If i manuel upload a file in the Lake the trigger fires.

Torsten

**Comment by jiyada** [comment]
Most likely issue is in the filter define on the blob storage event ? By default filter may be filtering out contentSize > 0 and it may be possible that when a new blob is created its getting missed.

**Comment by jiyada** [comment]
closing the issue with comment. please open it back if not fixed
