### ISSUE TITLE
CDMUtil - DefaultStringLenght- Typo

### ISSUE THREAD

**Issue by gregorosaurus** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#64]
Hello! 

Looks like the CDM Util config parameter "DefaultStringLenght" is misspelled.  Found this in the latest update, when trying to set the default string length to 1000 via the configuration. :) 

```
string DefaultStringLenght = getConfigurationValue(req, "DefaultStringLenght", ManifestURL);
            
if (DefaultStringLenght != null)
{
    AppConfiguration.synapseOptions.DefaultStringLenght = Int16.Parse(DefaultStringLenght);
}
```

Thanks!

**Comment by jiyada** [comment]
Fixed in the latest update
