### ISSUE TITLE
Issue Building CDMUtils project.

### ISSUE THREAD

**Issue by BlueMonday-Donovan-Wilson** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#65]
Hi I am rather stumped by this one and hoping someone can help me out.

I am following the "Deploy CDMUtil as Function App" example as described by the readme @ https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/master/Analytics/CDMUtilSolution/deploycdmutil.md

I have installed Visual Studio as well as dotnet from the prescribed link: https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net462-developer-pack-offline-installer

I opened the Microsoft.CommonDataModel.sln file with Visual Studio.

However on build, I receive the following error:
MSB3027: Could not copy "C:\Users\User\.nuget\packages\system.security.cryptography.protecteddata\5.0.0-preview.7.20364.11\runtimes\win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll" to "bin\Debug\netcoreapp3.1\runtimes\win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll".

I check and the file that is being copied does exist at the path described above, however the copy seems to fail. 

I check the path that the file should be copied to, namely "bin\Debug\netcoreapp3.1\runtimes\win\lib\netstandard2.0\" and the path only exists up to "bin\Debug\netcoreapp3.1"
I didn't think this was the problem, but I thought I would mention it.

Please, if anyone can help me. I am not to sure where to even start here.

**Comment by gregorosaurus** [comment]
Disclaimer: I'm not the maintainer of the repo. 

Make sure you have dotnet core 3.1 sdk installed (though that shouldve been installed with visual studio).  The CDMUtil is built against this version of dotnet core. 
(https://dotnet.microsoft.com/download/dotnet/3.1)[https://dotnet.microsoft.com/download/dotnet/3.1] 
Which visual studio version do you have? 2019?

**Comment by BlueMonday-Donovan-Wilson** [comment]
Issue was resolved by cloning the project, instead of downloading the zip. Not sure why this resolved the problem but it's working now.

**Comment by BHFOSA** [comment]
Your filenames were too long to do the copy. If you save your repo somewhere with a shorter name it will be successful. Windows has a max char limit on the directory path.
