### ISSUE TITLE
CDMUtil - Issue creating on-demand views 

### ISSUE THREAD

**Issue by tabuckingham** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#66]
We are running into issue with the CDMUtil solution when attempting to automate the Synapse On-Demand view creation. We have deployed this via an Azure Function App. The function app has been granted the required Storage Account roles and we have added the TenantId and SQLConnection parameters in the Function App configuration and verified that each are correct.

**ERROR**: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections

Is the AXDBConnection parameter required in our Function App configuration as well? Im unsure if the error is related to the AXDB SQL server or if it is related to our Synapse On-demand SQL endpoint.

**Comment by jiyada** [comment]
Most likely error is due to AXDBConnection  if its not reachable from functionApp. Its not mandatory paramater so you can remove it from configuration and try it again

**Comment by jiyada** [comment]
Closing the issue with comment.
