### ISSUE TITLE
CDMUtil - Date data type difference between Console App and Function App when using on-demand views

### ISSUE THREAD

**Issue by fireRoads** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#74]
I have used CDMUtil to expose data lake tables as on-demand views in Synapse. However, when using the function app I get conversion fails on all date fields: "Conversion failed when converting date and/or time from character string."

I have seen that the function app uses DATETIME as data type in the view but when using the console app it uses DATETIME2. The view created by the console app with DATETIME2 works but the function app view with DATETIME fails. 

Why is there a difference?

I am using the same settings in both scenarios.

**Comment by jiyada** [comment]
this was fixed couple of days back. can you get the latest code and update the functionApp ?
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/commit/27d84c8e15455eb71cdd108dfc6a2d970b1e2655#diff-4078935a0a9eabb6d4ebf1c31fb6108abfa5137e5f891acd26fb04ca3854bacc

**Comment by jiyada** [comment]
In Synapse serverless depending on the parser version (1.0 or 2.0 ) used for CSV - there are some differences how the datetime is supported. For example parser version 2 only support datetime2. with the new parameter - i have attempted to streamline the datetime datatype issue. At the high level now CDMUtil will  do following parser version  1.0 =  datetime ,  2.0 = datetime2. please re-open if you still see any issue.
