### ISSUE TITLE
Serverless View Decimal Precision & Scale Defaults to 18,0

### ISSUE THREAD

**Issue by gregorosaurus** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#81]
Hey there!

It looks like CDM -> SQL doesn't set the precision and scale in the conversion process. 
It defaults to "decimal" as the type, which sets the precision and scale to 18,0.  This is causing the queries to drop off the decimal points.

![2021-12-14 11_05_07-](https://user-images.githubusercontent.com/38509083/146055347-15293dbe-e4a0-4cab-b539-eeb9b07d6b6a.png)

Thanks!

**Comment by gpitzalis** [comment]
I have the same Issue. Have you ever tested the function?!?!?

**Comment by jiyada** [comment]
Fixed in the latest version. Please try latest version of console app or deploy latest code to azure function. Closing the issue with comment. Please re-open in case of issue.
