### ISSUE TITLE
Error handling external file: 'Max errors count reached.'

### ISSUE THREAD

**Issue by gpitzalis** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#82]
Hi guys,

I'm currently facing with this issue:

Error handling external file: 'Max errors count reached.'. File/External table name: 'https://xxx.dfs.core.windows.net/dynamics365-financeandoperations/eu-uat.sandbox.operations.dynamics.com/Tables/SupplyChain/SalesAndMarketing/WorksheetLine/SalesLine/SALESLINE_00001.csv'.

Please fix asap!
JP

**Comment by gregorosaurus** [comment]
Disclaimer: I'm not the maintainer of the project. 

This is more an issue with synapse's not great error messaging.
But this has happened to be sometimes when:
1) The data length of the serverless view for the column is too small (defaults to 100, but maybe you need 1000).  Try updating the length of the nvarchar to 1000 or some large number just to test. 
2) The data is not in the expected format in the columns that the data type matches.  Try changing all data columns to NVARCHAR(1000) just for testing. 


Try selecting column by column to see which one is having issues.  That's what I've done in the past.

**Comment by gpitzalis** [comment]
> Disclaimer: I'm not the maintainer of the project.
> 
> This is more an issue with synapse's not great error messaging. But this has happened to be sometimes when:
> 
> 1. The data length of the serverless view for the column is too small (defaults to 100, but maybe you need 1000).  Try updating the length of the nvarchar to 1000 or some large number just to test.
> 2. The data is not in the expected format in the columns that the data type matches.  Try changing all data columns to NVARCHAR(1000) just for testing.
> 
> Try selecting column by column to see which one is having issues. That's what I've done in the past.

Hi @gregorosaurus,

I already knew that! But columns length are automatically set by the Azure Function...

Do you know how to set default types length?

**Comment by rt112000** [comment]
> > Disclaimer: I'm not the maintainer of the project.
> > This is more an issue with synapse's not great error messaging. But this has happened to be sometimes when:
> > 
> > 1. The data length of the serverless view for the column is too small (defaults to 100, but maybe you need 1000).  Try updating the length of the nvarchar to 1000 or some large number just to test.
> > 2. The data is not in the expected format in the columns that the data type matches.  Try changing all data columns to NVARCHAR(1000) just for testing.
> > 
> > Try selecting column by column to see which one is having issues. That's what I've done in the past.
> 
> Hi @gregorosaurus,
> 
> I already knew that! But columns length are automatically set by the Azure Function...
> 
> Do you know how to set default types length?

Disclaimer: I'm not the maintainer of the project.

I believe you can set it at the "Application settings" of your Azure Function App. Add a new setting:
Name: DefaultStringLength
Value: 1000 or some large number just to test.

Please let us know how it goes for you.

See https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/master/Analytics/CDMUtilSolution/deploycdmutil.md

**Comment by gregorosaurus** [comment]
Yup, the DefaultStringLength parameter is what you're looking for. 
It can be set via the HTTP headers of calling the Azure function, if deployed that way, or using the app.config file to set it.

**Comment by jiyada** [comment]
Just to explain - earlier version of the CDMUtil by default using CSV Parser version = 2.0 for performance reason. parser version 2.0 provides improved performance, however have limited error handling specially in such scenario like string length or data type mismatch. new version of cdmutil we still have parser version 2 as default however you can now switch to parser version 1 to identify such issues easily.

**Comment by jiyada** [comment]
Closing the issue with comment - reopen if required.
