### ISSUE TITLE
ChangeFeed Files

### ISSUE THREAD

**Issue by scleynen** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#85]
In Analytics/SynapseToSQL_ADF one of the steps is

Run Console Application and create views for Tables (in dbo schema) and ChangeFeed files( CDC schema)

But when I do this the first part is done (Views in dbo schema) but the second part I can't find (CDC schema). Maybe I'm missing some configuration, but should there also be some views created in the CDC schema?

**Comment by jiyada** [comment]
you need to change the manifest file path to changeFeed folder and overide the schema to cdc to create changefeed folder table on cdc schema
