### ISSUE TITLE
SynapseToSQL_ADF - @TargetTable param is not compatible between Synapse  and Stored Procedure

### ISSUE THREAD

**Issue by ErdemJJFS** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#88]
- Analytics/SynapseToSQL_ADF/SynapseToSQL_TemplateForDataFactory.json vs 
  Analytics/SynapseToSQL_ADF/SynapseToSQL_DestSetupScript.sql (MergeCDC stored procedure params) - 

Synapse TargetTable param is not working with the MergeCDC stored procedure. Stored procedure expects it to be without the schema, however TargetTable param in the synapse is with schema. As a result, synapse completes the incremental updates successfully, however the tables are not updated accordingly.

Synapse TargetTable  Param:
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_TemplateForDataFactory.json#L545

Stored Procedure TargetTable Param:
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_DestSetupScript.sql#L70

https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_DestSetupScript.sql#L71

**Comment by ErdemJJFS** [comment]
dropping the schema @{last(split(pipeline().parameters.TABLE_NAME,'.'))} for the synapse @TargetTable param solves the problem for my end.

https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_TemplateForDataFactory.json#L545

**Comment by jiyada** [comment]
Updated the solution of Synapse To SQL pipeline https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/tree/master/Analytics/SynapseToSQL_ADF .. now it uses utilize Synapse pileline script utility to streamline the pipeline code and deployment process .. take a look if this helps..
