### ISSUE TITLE
SynapseToSQL_ADF - SynapseToSQL_DestSetupScript.sql - Column Names Size are not synced

### ISSUE THREAD

**Issue by ErdemJJFS** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#90]
The size of the ColumnNames are not the same, gets problematic when the size goes beyond 4K char even the table accepts up to 8K.

https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_DestSetupScript.sql#L21

https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_DestSetupScript.sql#L101

https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_DestSetupScript.sql#L112

**Comment by jiyada** [comment]
updated to match
