### ISSUE TITLE
SynapseToSQL_ADF - DataLake file name's naming strategy differs for Tables and ChangeFeed causing pipeline failures for incremental updates

### ISSUE THREAD

**Issue by ErdemJJFS** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#91]
data lake file names vary for Tables folder
data lake file names are all capital for ChangeFeed folder

<img width="536" alt="Screenshot 2022-01-27 at 02 45 08" src="https://user-images.githubusercontent.com/7804668/151282837-693195b0-7a79-4e38-a21e-6f0ad6bde6a8.png">
<img width="676" alt="Screenshot 2022-01-27 at 02 43 57" src="https://user-images.githubusercontent.com/7804668/151282851-ed42e8af-b65f-406a-a399-ff9f52e5ad03.png">

However the FullExport_SQL Pipeline uses FileName 
( https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_TemplateForDataFactory.json#L875 )

as the table name to generate columns TableName and CDCTableName in SynapseToSQLTable.
(
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/0f8769074e1c1bab26ad45efe36b5cdb1db91066/Analytics/SynapseToSQL_ADF/SynapseToSQL_TemplateForDataFactory.json#L191
)
As a result, the pipelines for the  incremental updates are failing.

modifying the SynapseToSQL_TemplateForDataFactory.json#L191 to @{pipeline().parameters.CDC_SCHEMA}.@{toUpper(activity('GetMetadata').output.firstRow.TABLE_NAME)} solves the issue I am having.

**Comment by jiyada** [comment]
Files name's naming strategy got aligned in the service with enhanced metadata features.
