### ISSUE TITLE
D365 table that contains metadata on D365 Export to Data Lake table list, status and errors

### ISSUE THREAD

**Issue by LJG5000** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#96]
CDM Util relies on a Synapse event trigger to detect new manifest files when a table is activated. This in turn triggers a series of processes to populate a control table, generate the external views or tables associated with this table, etc. 

Are there D365 tables that can be accessed or other methods that can:

(1) Show when a table was deactivated. The CDM Util code does not support this directly. It is also important to know when a table has been reinitialized, i.e, when it changes from running to deactivated to activated (running).
(2) Show a list of all running tables (activated tables). These are tables that have CDC enabled in D365.
(3) Capture error codes associated with the Export to Data lake process, for example, those arising from corrupted CSV files, or when new columns are added to an activated tables.

While the above is not strictly related to existing CDM Util code- any assistance in approach

**Comment by jiyada** [comment]
The best way to solve this will be Business events preview feature that is in preview .. check the yammer thread for more details. 
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1581288875966464
