### ISSUE TITLE
Database Name not quoted when creating database

### ISSUE THREAD

**Issue by dan-we** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#98]
https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/blob/e7859c149ef58829ec992938611366d9ba489922/Analytics/CDMUtilSolution/CDMUtil/SQL/SQLHandler.cs#L585

The database name is not quoted after `create database`, which causes an issue if the database name contains a hyphen (or possibly other characters).  Exception message when the database name contains a hyphen is:
```Incorrect syntax near '-'.```

**Comment by jiyada** [comment]
fixed with latest release
